[project]
name = "proyecto-xia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alibi>=0.5.5",
    "anchor>=0.4.0",
    "anchor-exp>=0.0.2.0",
    "ipykernel>=7.2.0",
    "lime>=0.2.0.1",
    "matplotlib>=3.10.9",
    "numpy>=2.4.6",
    "openml>=0.15.1",
    "pandas>=3.0.3",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "shap>=0.51.0",
    "ucimlrepo>=0.0.7",
    "xgboost>=3.2.0",
]
